### PR TITLE
Internazionalization support

### PR DESCRIPTION
**Pull request by danydev**
This PR allows userland to either translate messages displayed to user or just customize them based on preferences. 
By default nearly nothing is changed (except for a new message when read successfully), but user of the library can now define a callback to override messages shown in the UI

Usage is pretty simple: just define new callback `customAlertMessage` that receives an `AlertMessage` and returns a `String` for the given alert message:
```
passportReader.readPassport(mrzKey: mrzKey, customAlertMessage: { (alertMessage) in
    switch(alertMessage) {
    case AlertMessage.HoldYourPhoneNearNFCDocument:
        return "Hold your device near a NFC document"
    case AlertMessage.AuthenticatingPassport(_), AlertMessage.ReadingDataGroup(_, _), AlertMessage.ReadingPassport:
        return "Reading Document..."
    case AlertMessage.SuccessfulRead:
        return "Document read successfully"
    case AlertMessage.Error(_):
        return "Error while reading document. Please try again." // Note how we could use the given error to show more precise messages if needed
  }, completed: { (passport, error) in
        // ...
}})
```

CC: @AndyQ

### CODE REVIEW

**Comment by danydev** [comment]
@AndyQ what do you think about it?

**Comment by AndyQ** [comment]
I have looked and and am just considering whether it should be using the system localisation or not, and if so  - how!

I do like the idea though!

**Comment by danydev** [comment]
I see what you mean. Using `NSLocalizedString` is generally the good way to provide localized messages. Still this PR allows the user to customize the message, not just translating it. Translating is just a side effect of this feature.
In my vision `NSLocalizedString` should be called from userland with its own string. You could still use NSLocalizedString to provide safe defaults for different languages, but that would be just a convenience for the users to avoid translating themselves the default messages.

For example in my app I don't want to show "Reading DG1..." because people using my app don't know what a data group is :)

**Comment by AndyQ** [comment]
Thanks - Having thought about it I'm in agreement so  I'm merging this and will be in the next version.

I'm going to change a couple of names and types though.
e.g.
AlertDisplayMessage -> NFCViewDisplayMessage, and the values are changing - mainly for lowercase first letter but also for more consistency - e.g. HoldYourPhoneNearNFCDocument -> requestPresentPassport.

I've also fixed a slight issue where if displayed authenticatingPassport during reading the datagroups (long progress)

Thanks very much!

**Pull request merged**
