### PR TITLE
Add podspec to NFCPassportReader

### PR DESCRIPTION
**Pull request by ChristianNorbertBraun**
Makes the current lib work with Cocoapods.
The spec is not uploaded to the Cocoapod repo yet.

### CODE REVIEW

**Comment by AndyQ** [comment]
Thanks for this - I'm not ignoring it - I'm just contemplating whether to add this and more away from Swift Package Manager for the moment and just support CocoaPods, or stick with SPM.

Currently leaning towards Cocoapods as its more flexible than SPM at the moment but thinking......

**Comment by jonathanellis** [comment]
✚ Upvote for Cocoapods support! 😊

**Comment by ChristianNorbertBraun** [comment]
Hey there, just asking if you are still considering integrating Cocoapods?

**Comment by AndyQ** [comment]
I am indeed - my main issue though is that currently I can't support both Swift Package Manager and Cocoapods (at least not in the way I'd like) until there is either a way for SPM to support binaries or there is a SPM compatible version of OpenSSL!

Would be interested to know though how many people prefer Cocoapods over SPM!

**Comment by AndyQ** [comment]
After lots of thought, I've decided that to switch over to Cocoapods until SPM supports binary projects AND OpenSSL can be pulled in.

I've merged this pull request .

Thanks very much!

**Pull request closed without merging**
